Add paired and unpaired
MarioAriasC/funKTionale pull request #16
Opened 2016-11-02 21:25 UTC by jkpl

Extension methods similar to `uncurry`. Converts parameters between a pair value and a pair of parameters.

2016-11-09 09:58 UTC, MarioAriasC requested changes
It looks good but I'm not convinced about putting this on currying package. It should be in a different new package

2016-11-09 09:58 UTC, MarioAriasC commented on src/main/kotlin/org/funktionale/currying/namespace.kt
> +    return { p1: P1, p2: P2 -> this(Pair(p1, p2)) }
Is technically correct but Kotlin's idiomatic way to create `Pair<P1,P2>` is `p1 to p2` using the `to` extension function

2016-11-09 09:58 UTC, MarioAriasC commented on src/test/kotlin/org/funktionale/currying/CurryingTest.kt
> +        assertEquals(paired(Pair(5, 9)), unpaired(5, 9))
Same here and line 56

2016-11-09 10:16 UTC, jkpl commented on src/main/kotlin/org/funktionale/currying/namespace.kt
> +    return { p1: P1, p2: P2 -> this(Pair(p1, p2)) }
Cool. I'll update it. 👍

2016-11-23 16:46 UTC, MarioAriasC approved these changes
👍

2016-11-23 16:46 UTC, merged