Pipe operator implementation
MarioAriasC/funKTionale pull request #28
Opened 2017-04-28 16:08 UTC by BenjaminEarley

Passes the result of an expression as the first parameter of another expression.

2017-04-28 16:14 UTC, martin-g commented
Where are the tests ?!

2017-04-28 19:35 UTC, BenjaminEarley commented
@martin-g Thanks Martin. Is it convention here I implement this method out to 22 arguments?

2017-04-28 20:10 UTC, martin-g commented
I am not really sure! I am not a maintainer here, but just someone interested in Kotlin and FP.
But I think it is a convention. And I think it comes from Scala.

2017-04-29 09:32 UTC, MarioAriasC requested changes

2017-04-29 09:32 UTC, MarioAriasC commented on funktionale-experimental/pom.xml
> +        </dependency>
We don't use JUnit but TestNG, check the other modules for examples

2017-04-29 09:32 UTC, MarioAriasC commented on funktionale-experimental/src/test/kotlin/org/funktionale/pipe/PipeTest.kt
> +import org.junit.Test
Same here, no JUnit but TestNG

2017-04-29 09:32 UTC, MarioAriasC commented on funktionale-experimental/src/main/kotlin/org/funktionale/pipe/pipe.kt
> +infix inline fun <P1, P2, P3, P4> P1.pipe3(crossinline t: (P1, P2, P3) -> P4): (P2, P3) -> P4 = { p2, p3 -> t(this, p2, p3) }
Not sure about naming, I need to test it. But usually, I prefer just `pipe` instead of `pipeN` unless isn't possible to compile

2017-04-29 09:33 UTC, MarioAriasC commented
I need on your description a use case. Bonus points if is a realistic one

2017-04-29 15:58 UTC, BenjaminEarley commented
@MarioAriasC 

Piping is for composing operations in the order that they are performed. Left to right and top to bottom, instead of inside out. Languages like F# and Elixir have syntax for this.

### Simple Example: 

```
2 pipe { it + 1 } pipe { it * 2 }
```

### Real World Example from a common Rx use-case:

##### Before the magic of piping

```
disposables.add(
        fab
                .clicks()
                .switchMap {
                    ApiInterface
                            .getStuff(ids = retrofitListOf(1234))
                            .subscribeOn(Schedulers.io())
                            .toObservable()
                }
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe({ deals ->
                    Log.d("Debug", "Success: " + stuff.toString())
                }, { error ->
                    Log.d("Debug", "Error: " + stuff.toString())
                })
)
```

##### After

```
fab
    .clicks()
    .switchMap {
        ApiInterface
            .getStuff(ids = retrofitListOf(1234))
            .subscribeOn(Schedulers.io())
            .toObservable()
    }
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe({ deals ->
        Log.d("Debug", "Success: " + stuff.toString())
    }, { error ->
        Log.d("Debug", "Error: " + stuff.toString())
    }) pipe { disposables.add(it) }
```

2017-04-29 16:11 UTC, BenjaminEarley commented on funktionale-experimental/src/main/kotlin/org/funktionale/pipe/pipe.kt
> +infix inline fun <P1, P2, P3, P4> P1.pipe3(crossinline t: (P1, P2, P3) -> P4): (P2, P3) -> P4 = { p2, p3 -> t(this, p2, p3) }
The compiler can't determine which pipe function to use when the names are the same. I'd like to have them be the same name also. I'll do some research to see if there is a compiler hint for this.

2017-05-02 10:25 UTC, MarioAriasC commented
@jkpl check this out

2017-05-02 10:38 UTC, jkpl commented
Examples from other languages:

* [|> and <| in Elm](http://elm-lang.org/docs/syntax#infix-operators)
* [|> in OCaml](http://blog.shaynefletcher.org/2013/12/pipelining-with-operator-in-ocaml.html)

It's similar to reverse compose. I think it's pretty useful.

2017-05-02 10:40 UTC, jkpl commented
So instead of:

```kotlin
foo(bar(zap(x)))
```

You have:

```kotlin
zap(x).pipe(bar).pipe(foo)
```

2017-05-02 10:42 UTC, MarioAriasC requested changes

2017-05-02 10:42 UTC, MarioAriasC commented on funktionale-experimental/src/main/kotlin/org/funktionale/pipe/pipe.kt
> +infix inline fun <P1, P2, P3> P1.pipe2(crossinline t: (P1, P2) -> P3): (P2) -> P3 = { p2 -> t(this, p2) }
Return types should be `R` for consistency with the codebase

2017-05-04 10:39 UTC, MarioAriasC approved these changes

2017-05-04 10:39 UTC, merged

2017-06-05 10:45 UTC, MarioAriasC commented
Can you add a wiki page for ```pipe```? 

Cheers